name: "on_commit"
on: push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: lhjnilsson/foreverbull-python-action@v0.0.2
        with:
          path: .
          assets: 'aapl tsla msft'
          start: '2021-01-01'
          end: '2021-06-31'
          alpaca_key: ${{ secrets.ALPACA_KEY }}
          alpaca_secret: ${{ secrets.ALPACA_SECRET }}
